### ISSUE TITLE
SourceType: Local -> Next Button

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#14]
If `LOCAL` is selected in the SourceType-dropdown of editing or creating a resource, it should be possible to continue without selecting a backend-connection with the `NEXT` button. However, this button is always grayed out without selecting a backend-connection, independent of the source type selection.

Workaround here is simply to press the `BROKERS` tab directly instead of using the `NEXT` button (that always skips the check for selected backend-connection at this point).

![image](https://user-images.githubusercontent.com/75306992/110338700-9c579f00-8027-11eb-946f-8e053a79da4b.png)

**Comment by BastianWel** [comment]
@goekhanKahriman @juliapampus 
Is this possible or does our data model currently always require a backend connection?

**Comment by goekhanKahriman** [comment]
Because of the current implementation in CM, a BackendConnection is actually always needed, since the ID is used from this in several places. Therefore I would leave it at this point for now and not change anything. One reason for this is that there will be many changes in the CM in the next weeks.

Nevertheless, the comment of @tmberthold is not wrong, that this can be better implemented in the CM and the UI.
