### ISSUE TITLE
Additional registration of a resource at the broker not forwarded

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#7]
When editing a resource to register it at a broker, I set the tick and press `save` and nothing happens. A look into the console of GUI and Configmanager shows me that no matching call has been triggered.

**Comment by tmberthold** [comment]
Does not work under the following circumstances:
When editing a resource, the user can switch directly from the automatically opened `META DATA` tab to the `BROKERS` tab by clicking on the `BROKERS` tab instead of using the `NEXT` button. This procedure skips the `POLICY` and the `REPRESENTATION` tabs in the `NEXT`-sequence, which are apparently both necessary to be opened once for the `SAVE` button to actually work at the end. -> GUI

**Comment by BastianWel** [comment]
Yes, this is because vue components are not mounted until they were visible. I need to find a better solution there. Until then I will disable the direct click on the tabs.

**Comment by BastianWel** [comment]
Found a solution: Using `eager` loads all tab items on mount:
`<v-tab-item :eager="true">`
