### ISSUE TITLE
Missing source type on resource editing

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#8]
When editing a resource, one has to set the source type each and every time. Is this not being saved in the Configmanager @goekhanKahriman or does the GUI fail to load this information?

**Comment by tmberthold** [comment]
One possibility: Could be due to outdated JPA-database-table-schemas in the ConfigManager. By default, `spring.jpa.hibernate.ddl-auto=update` is set in the ConfigManager application-properties. This setting needs to be temporary switched to `create` or `create-drop`. After that the `update` setting could be used again. 

_JPA Hibernate Update: "the object model created based on the mappings (annotations or XML) is compared with the existing schema, and then Hibernate updates the schema according to the diff. **It never deletes the existing tables or columns even if they are no more required by the application**"_ https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

Generally leads to problems, because often in this context `saveAndFlush` is used to persist data in the DB, but then the DB-schemas do not fit anymore or too many old outdated db-schemes are present blocking heap-space when only using update. (In the ConfigManager this would be in the ConfigModelService saveStat() for example, which would simply stop working). Due to the ongoing development of the ConfigManager, the schemas could be changing.

Could be a possibility, however, we are looking for a sustainable solution here. The source of the issue will probably be the ConfigManager and not the UI.

**Comment by BastianWel** [comment]
Source types are missing for all resources that CM loads from the Connector at startup because this info does not exist in the info model.

**Comment by tmberthold** [comment]
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/issues/22

**Comment by BastianWel** [comment]
Source type removed from resource representation page with commit 3985942
